### ISSUE TITLE
Migrate from agile course to teamwork course.

### ISSUE THREAD

**Issue by svenvanderburg** [escience-academy/lesson-agile-escience#22]
Look through existing material, see what we have to change to make this a teamwork course instead of agile course. Create new issues, or for small changes create a new PR.

**Comment by raar1** [comment]
My preliminary thoughts:
* Episode 1 is somewhat neutral ("Teamwork" compatible), but every other Episode is about Agile ways of working. This makes sense, since planning and team coordination is core to how working in a team happens. However, as it stands, it is an Agile course with a Teamwork intro episode.
* The immediate question is then, what (teachable) aspects of teamworking are not related to planning/coordination. Perhaps we need an Episode on those issues? These could include interpersonal skills/relationships, conflict resolution etc.

**Comment by raar1** [comment]
How about a section on Feedback:
- In this case, it refers to one-on-one feedback, so as not to cover the feddback normally given in sprint retrospectives
- Why is it important to ask for and receive feedback.
- How to give feedback constructively

It's a bit vague, but I think this is what is missing in terms of making the course about teamwork. If there is agreement then I can make this proposed Episode a new issue.

**Comment by svenvanderburg** [comment]
As discussed I created:
* #29 
* #30
